### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'qos'

### ISSUE THREAD

**Issue by tsoodla** [matthewwall/weewx-mqtt#2]
Hi! If you need more information, just ask.
Thank you :)

Feb 15 12:54:32 pi3 systemd[1]: Starting LSB: weewx weather system...
Feb 15 12:54:32 pi3 weewx[30696]: engine: Initializing weewx version 3.9.2
Feb 15 12:54:32 pi3 weewx[30696]: engine: Using Python 2.7.16 (default, Oct 10 2019, 22:02:15) #012[GCC 8.3.0]
Feb 15 12:54:32 pi3 weewx[30696]: engine: Platform Linux-4.19.97-v7+-armv7l-with-debian-10.3
Feb 15 12:54:32 pi3 weewx[30696]: engine: Locale is 'en_GB.UTF-8'
Feb 15 12:54:32 pi3 weewx[30696]: engine: pid file is /var/run/weewx.pid
Feb 15 12:54:32 pi3 weewx[30700]: engine: Using configuration file /home/weewx/weewx.conf
Feb 15 12:54:32 pi3 weewx[30700]: engine: Loading station type Vantage (weewx.drivers.vantage)
Feb 15 12:54:32 pi3 weewx[30686]: Starting weewx weather system: weewx.
Feb 15 12:54:32 pi3 systemd[1]: Started LSB: weewx weather system.
Feb 15 12:54:36 pi3 weewx[30700]: engine: StdConvert target unit is 0x1
Feb 15 12:54:36 pi3 weewx[30700]: wxcalculate: The following values will be calculated: barometer=prefer_hardware, windchill=prefer_hardware, dewpoint=prefer_hardware, appTemp=prefer_hardware, rainRate=prefer_hardware, windrun=prefer_hardware, heatindex=prefer_hardware, maxSolarRad=prefer_hardware, humidex=prefer_hardware, pressure=prefer_hardware, inDewpoint=prefer_hardware, ET=prefer_hardware, altimeter=prefer_hardware, cloudbase=prefer_hardware
Feb 15 12:54:36 pi3 weewx[30700]: wxcalculate: The following algorithms will be used for calculations: altimeter=aaNOAA, maxSolarRad=RS
Feb 15 12:54:36 pi3 weewx[30700]: Luxtronik: heatpump 192.168.201.40:8889
Feb 15 12:54:36 pi3 weewx[30700]: engine: Archive will use data binding wx_binding
Feb 15 12:54:36 pi3 weewx[30700]: engine: Record generation will be attempted in 'hardware'
Feb 15 12:54:36 pi3 weewx[30700]: engine: Using archive interval of 300 seconds (specified by hardware)
Feb 15 12:54:36 pi3 weewx[30700]: engine: Using binding 'wx_binding' to database 'weewx.sdb'
Feb 15 12:54:36 pi3 weewx[30700]: manager: Starting backfill of daily summaries
Feb 15 12:54:36 pi3 weewx[30700]: restx: StationRegistry: Station will be registered.
Feb 15 12:54:36 pi3 weewx[30700]: restx: MQTT: service version is 0.20
Feb 15 12:54:36 pi3 weewx[30700]: restx: MQTT: binding to loop
Feb 15 12:54:36 pi3 weewx[30700]: engine: Caught unrecoverable exception in engine:
Feb 15 12:54:36 pi3 weewx[30700]:     ****  __init__() got an unexpected keyword argument 'qos'
Feb 15 12:54:36 pi3 weewx[30700]:     ****  Traceback (most recent call last):
Feb 15 12:54:36 pi3 weewx[30700]:     ****    File "/home/weewx/bin/weewx/engine.py", line 888, in main
Feb 15 12:54:36 pi3 weewx[30700]:     ****      engine = engine_class(config_dict)
Feb 15 12:54:36 pi3 weewx[30700]:     ****    File "/home/weewx/bin/weewx/engine.py", line 78, in __init__
Feb 15 12:54:36 pi3 weewx[30700]:     ****      self.loadServices(config_dict)
Feb 15 12:54:36 pi3 weewx[30700]:     ****    File "/home/weewx/bin/weewx/engine.py", line 142, in loadServices
Feb 15 12:54:36 pi3 weewx[30700]:     ****      self.service_obj.append(weeutil.weeutil._get_object(svc)(self, config_dict))
Feb 15 12:54:36 pi3 weewx[30700]:     ****    File "/home/weewx/bin/user/mqtt.py", line 260, in __init__
Feb 15 12:54:36 pi3 weewx[30700]:     ****      self.archive_thread = MQTTThread(self.archive_queue, **site_dict)
Feb 15 12:54:36 pi3 weewx[30700]:     ****  TypeError: __init__() got an unexpected keyword argument 'qos'
Feb 15 12:54:36 pi3 weewx[30700]:     ****  Exiting.

**Comment by europacafe** [comment]
Hi, how did you define qos in weewx config? I'm curious to try too.

**Comment by tsoodla** [comment]
I am not using qos.
