### ISSUE TITLE
Update interval

### ISSUE THREAD

**Issue by aleqcz** [matthewwall/weewx-mqtt#27]
Hi,
I have a PWS which sends data every 12 seconds, I wonder is there a way to freshen MQTT values earlier than every 5 minutes? If yes, what do I need to set and where?

Thanks a lot,
A.

**Comment by ajay10000** [comment]
@aleqcz, I believe this is controlled by weewx `archive_interval` or the hardware.  See http://www.weewx.com/docs/usersguide.htm#StdArchive.

**Comment by PaulWieland** [comment]
I have the same question. My `archive_interval` is 300 seconds (5 minutes). The plugin is only publishing to MQTT every 30 minutes.

**Comment by matthewwall** [comment]
configure the mqtt uploader to send 'loop' data (default is to send only 'archive' data).  then you will see mqtt data as soon as your station sends it.

if mqtt is sending every 30 minutes, that probably means that your weewx instance uses an archive interval of 30 minutes, which it probably got from your hardware.  see the weewx docs for how to change the archive interval for your hardware.
