### ISSUE TITLE
weather/loop does not contain windDir

### ISSUE THREAD

**Issue by mymaestro** [matthewwall/weewx-mqtt#34]
weather/windDir gets pulblished, but weather/loop JSON does not contain windDir

**Comment by matthewwall** [comment]
is wind speed zero?

wind speed is undefined when wind speed is zero.  see the windDir section in StdWXCalculate in the weewx user guide.

**Comment by mymaestro** [comment]
That explains it, thanks. Working.

**Comment by ThomDietrich** [comment]
Hey @matthewwall,

not sure whether this is related. Any idea why my setup doesn't report windDir?

Weewx receives it from my weather station:

![image](https://user-images.githubusercontent.com/2870104/189547822-c226ba87-5af8-46eb-bcc2-d4f7ffceb9ba.png)

But the extension doesn't report it via MQTT:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/2870104/189547882-75a63639-1619-47f3-a314-14fd1457ed49.png">

**Comment by mymaestro** [comment]
For me windDir shows up only when there is wind speed

**Comment by ThomDietrich** [comment]
I have Home Assistant subscribed to "weather/windDir" and it didn't see a single measurement over multiple months. Based on that I don't think it shows up for me at all...

**Comment by roe-dl** [comment]
In my installation `windDir` is included in MQTT output. If you did not exclude `windDir` from being included in the MQTT output in the `[[inputs]]` section, then I guess, the reason is not within the weewx-mqtt extension but elsewhere.

**Comment by ThomDietrich** [comment]
Resolved.
@roe-dl I didn't want to believe it but there was indeed an old config element that was responsible. I must have copied this from https://github.com/matthewwall/weewx-mqtt/issues/5:

```
[[[[windDir]]]]
    format = directions
```

It is working now. I intend to put in a few minutes for investigation to find out whether an error message could have saved me from the trouble, might propose a PR. Resolved for now. Thanks guys.
