### ISSUE TITLE
paho for python3

### ISSUE THREAD

**Issue by tsoodla** [matthewwall/weewx-mqtt#6]
please add `pip3 install paho-mqtt` or `sudo python3 -m pip install paho-mqtt` to readme to support weewx4 in py3

**Comment by cclarke99** [comment]
> please add `pip3 install paho-mqtt` or `sudo python3 -m pip install paho-mqtt` to readme to support weewx4 in py3

Thank you for taking the time to add this issue here -- helped me get things working again!

**Comment by matthewwall** [comment]
fixed at commit 80575b8
