### ISSUE TITLE
Air Quality

### ISSUE THREAD

**Issue by dshanske** [matthewwall/weewx-mqtt#7]
I just added pm2_5 and pm10_0 data to my system, but I'm not seeing that in the Weewx Topic. Was wondering if there is a method to set this?

**Comment by matthewwall** [comment]
the default binding for mqtt is 'archive', so if you added `pm2_5` and `pm10_0` only to loop records (i.e., you did not add it to your schema), then you will not see it in the mqtt publishes.

either set the binding in mqtt extension to 'loop', or extend your weewx database to include those two fields.  or use the wview_extended schema (part of weewx4), which includes the particulate observations.

if you have further questions, please post on the weewx user group.  this is for bug reports.
