### ISSUE TITLE
MQTT connection allways closed after sending data

### ISSUE THREAD

**Issue by Wildbill-Z** [matthewwall/weewx-mqtt#9]
Hi,
I tried to get data from weewx to a smarthome system called iobroker which also has a MQTT-Client. All worked well, but it seems, that the connection is allways closed after sending data and reopend new when next packet is ready. This causes the MQTT-Adapter in iobroker to display a (wrong) faulty state and allways writing a message in the log (see below).
Is there a chance to get the weewx-mqtt-adapter to not close the connection after sending?
Here my log in iobroker:
`

mqtt.0 | 2020-06-07 20:51:15.323 | info | (27911) Client [weewx_5d5f1a2c] connection closed: disconnected
-- | -- | -- | --
mqtt.0 | 2020-06-07 20:51:15.284 | info | (27911) Client [weewx_5d5f1a2c] connected with secret 1591555875283_6890
mqtt.0 | 2020-06-07 20:50:15.314 | info | (27911) Client [weewx_f6d54340] connection closed: disconnected
mqtt.0 | 2020-06-07 20:50:15.281 | info | (27911) Client [weewx_f6d54340] connected with secret 1591555815280_2309
mqtt.0 | 2020-06-07 20:49:15.327 | info | (27911) Client [weewx_295950fc] connection closed: disconnected
mqtt.0 | 2020-06-07 20:49:15.280 | info | (27911) Client [weewx_295950fc] connected with secret 1591555755279_2078
mqtt.0 | 2020-06-07 20:48:15.327 | info | (27911) Client [weewx_6f85f9bc] connection closed: disconnected
mqtt.0 | 2020-06-07 20:48:15.276 | info | (27911) Client [weewx_6f85f9bc] connected with secret 1591555695276_1289

`
Log in weewx is unsuspicious and all is working well, all data seems plausible and correct. Only the wrong state in iobroker and the log messages (which I could remove by setting log level to warn or error but thats not the point) are a bit of disturbing to me.
Greetings, Jürgen

**Comment by ralight** [comment]
I agree. This behaviour is really rather annoying. Watching the logs of test.mosquitto.org I see lots of connections per second from this, all from a relatively few number of clients. Changing the behaviour to connect and call loop_start() when the module starts, then calling publish as required, would basically remove all of those extra connections.

This might seem like a fairly trivial point that is only a bit annoying because it's "not the right way of doing things", but it can have big performance considerations. If you have TLS enabled, then making a fresh connection is CPU intensive. If you are making a new connection for each publish, then the cost of the TLS handshake will be the dominant use of CPU in the whole of the broker. In this example, 50% of the CPU use was on TLS handshakes due to this same behaviour: https://groups.google.com/a/chromium.org/g/proto-quic/c/93fc-EPj0IQ

**Comment by digitalurban** [comment]
I am getting the same issue - it disconnects after each publish, so every 3 seconds and then reconnects - my server logs are full of weewx disconnects.

Is there any way this could be addressed?

**Comment by ralight** [comment]
This image shows the impact on processor usage if 10 messages are sent in a single connection or in multiple connections. The difference is huge. https://twitter.com/MosquittoMQTT/status/1293935424818352130

**Comment by dseven** [comment]
I've made an *experimental* fork, with a change to establish a reusable MQTT client. So-far, it's working for me, including automatically reestablishing the connection after the broker goes down for a while. The author probably had some reason for establishing a new client for each loop iteration, so this may be a non-starter, but it'd be interesting to hear what the reasoning was... or/and hear if this experimental version works for others....

https://github.com/dseven/weewx-mqtt/tree/reusable-mqtt-client

(be sure to use the reusable-mqtt-client branch)

**Comment by Wildbill-Z** [comment]
@dseven Tried your fork and it seems to work pretty good. Just got one first message as weewx was connecting to the broker and then no more. 
I think you should place a pull request. Maybe @matthewwall merges it into his offivial branch.
Nevertheless, I'll close this issue in a few days as it seems solved (at least for me). But I'll wait if someone else has any problems or tells that all is working fine.
Thank you very much!

Greetings, Jürgen

**Comment by ralight** [comment]
@Wildbill-Z I would suggest that you don't close this issue until it is fixed in this repository, otherwise other people may not benefit.

**Comment by Wildbill-Z** [comment]
Yes, you are right. But as @matthewwall didn't respond since June last year, I do not have any hope, that there will be an update...
I'll leave it in open state, we will see.

Greetings, Jürgen

**Comment by dseven** [comment]
Agree that we should keep this issue open for now. I may do a PR after a bit of "soak time". I'm concerned that there's some failure case that I haven't thought of / encountered yet.

Thanks for confirming that it's working for you, Jürgen!

**Comment by dseven** [comment]
I've pushed [an update](https://github.com/dseven/weewx-mqtt/commit/38899801b5428562a826727c656bf1b602b79926) to my branch to cover the case where the MQTT broker is unreachable at the time weewxd is started. Please test this or/and comment, if you feel so inclined.

**Comment by Wildbill-Z** [comment]
Seems to work. I tested by stopping weewx, stopping my mosquitto-ct, started weewx, got error message that mqtt-broker not available, then started mosquitto and connection was established automatically. All values going down their way to mosquitto without problem again. :+1: 

`Jan 20 21:21:32 weewx-davis-ct python2[3237]: weewx[3237] ERROR user.mqtt: Failed to connect to MQTT server (mqtt://xxx:xxx@192.168.10.185:1883/): [Errno 113] No route to host
Jan 20 21:21:32 weewx-davis-ct python2[3237]: weewx[3237] ERROR weewx.restx: MQTT: Failed to publish record 2021-01-20 21:21:00 CET (1611174060): MQTT client not available
Jan 20 21:22:16 weewx-davis-ct python2[3237]: weewx[3237] INFO user.mqtt: client established for mqtt://xxx:xxx@192.168.10.185:1883/`

Greetings, Jürgen
